### ISSUE TITLE
merhaba 

### ISSUE THREAD

**Issue by chKBlitz** [abdullahcaliskan/stok-yonetim#1]
merhaba stok yönetim yazılımınızda sql dosyasını bulamadım paylaşmanız mümkünmüdür ?

**Comment by chKBlitz** [comment]
kullanmak için istiyorum paylaşmak değil :)

**Comment by xsetra** [comment]
çok önceden yazdığım bir uygulama, sql export almadan atmışım. dosya bende de yok.
